# spring.application.name=backend
#  config port
server:
  port: 8080
  servlet:
    context-path: /identity

#  Config cau hinh database
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lumina_book
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  # Chi dung jpa duoi day de tu dong tao table User, tuy nhien khi di lam can dua vao 1 script SQL
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
#  Brevo Email Configuration
brevo:
  api:
    key: ${BREVO_API_KEY}
  sender:
    email: ${BREVO_EMAIL} # Email ?? verify trong Brevo

#  Secret Key
jwt:
  signerKey: "/nvphzRqEgduNfnKy2ztU3XBeojbmK8jzDivxOxLIGnl+D5GfkjyXdLq15xz9af/\n"
  valid-duration: 3600  # in second
  refreshable-duration: 360000 # in seconds

Layer1 - Controller: Quan ly cac mapping, endpoint
Layer2 - Service: Xu ly cac logic lien quan toi subdomain
Layer3 - Repository: Tang tuong tac truc tiep voi DBMS
